"""models update

Revision ID: 5881ca1d0bd8
Revises: ee4a6a96f3e2
Create Date: 2026-07-21 02:21:26.030044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5881ca1d0bd8'
down_revision: Union[str, None] = 'ee4a6a96f3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paiements', sa.Column('quitus_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_paiements_quitus_id_quitus'), 'paiements', 'quitus', ['quitus_id'], ['id'])
    op.drop_column('paiements', 'quitus_file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paiements', sa.Column('quitus_file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_paiements_quitus_id_quitus'), 'paiements', type_='foreignkey')
    op.drop_column('paiements', 'quitus_id')
    # ### end Alembic commands ###
