"""little update

Revision ID: 8b14769032f5
Revises: 5881ca1d0bd8
Create Date: 2026-07-21 20:59:55.107455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b14769032f5'
down_revision: Union[str, None] = '5881ca1d0bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objets_paiement', 'echeance',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('paiements', sa.Column('objet_paiement_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_paiements_objet_paiement_id_objets_paiement'), 'paiements', 'objets_paiement', ['objet_paiement_id'], ['id'])
    op.drop_column('paiements', 'objet_paiement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paiements', sa.Column('objet_paiement', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_paiements_objet_paiement_id_objets_paiement'), 'paiements', type_='foreignkey')
    op.drop_column('paiements', 'objet_paiement_id')
    op.alter_column('objets_paiement', 'echeance',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
