"""adds

Revision ID: a11a56249520
Revises: 8b14769032f5
Create Date: 2026-07-22 01:17:12.349024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11a56249520'
down_revision: Union[str, None] = '8b14769032f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paiements', sa.Column('numero_recu', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_paiements_numero_recu'), 'paiements', ['numero_recu'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_paiements_numero_recu'), 'paiements', type_='unique')
    op.drop_column('paiements', 'numero_recu')
    # ### end Alembic commands ###
