"""initial schema

Revision ID: da2cde4bfd36
Revises: 
Create Date: 2026-07-18 13:58:56.279830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2cde4bfd36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etablissements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email_contact', sa.String(length=150), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etablissements')),
    sa.UniqueConstraint('code', name=op.f('uq_etablissements_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('matricule', sa.String(length=30), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'etablissement', 'apprenant', 'caisse', name='roleutilisateur'), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('etablissement_id', sa.UUID(), nullable=True),
    sa.Column('filiere', sa.String(length=100), nullable=True),
    sa.Column('niveau', sa.String(length=20), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], name=op.f('fk_users_etablissement_id_etablissements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_matricule'), 'users', ['matricule'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apprenant_id', sa.UUID(), nullable=False),
    sa.Column('etablissement_id', sa.UUID(), nullable=False),
    sa.Column('objet_paiement', sa.String(length=100), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moyen_paiement', sa.Enum('orange_money', 'mtn_momo', 'carte_bancaire', name='moyenpaiement'), nullable=True),
    sa.Column('numero_compte_paiement', sa.String(length=20), nullable=True),
    sa.Column('email_paiement', sa.String(length=150), nullable=True),
    sa.Column('adresse_paiement', sa.String(length=255), nullable=True),
    sa.Column('ville_paiement', sa.String(length=100), nullable=True),
    sa.Column('code_postal_paiement', sa.String(length=20), nullable=True),
    sa.Column('quitus_file_path', sa.String(length=255), nullable=True),
    sa.Column('infos_extraites', sa.JSON(), nullable=True),
    sa.Column('infos_confirmees', sa.JSON(), nullable=True),
    sa.Column('statut', sa.Enum('brouillon', 'info_verifiee', 'moyen_defini', 'en_attente_operateur', 'proforma', 'en_file_caisse', 'acquittee', 'echouee', 'annulee', name='statutpaiement'), nullable=False),
    sa.Column('reference_transaction', sa.String(length=64), nullable=True),
    sa.Column('reference_operateur', sa.String(length=64), nullable=True),
    sa.Column('motif_echec', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('autorise_at', sa.DateTime(), nullable=True),
    sa.Column('acquitte_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apprenant_id'], ['users.id'], name=op.f('fk_paiements_apprenant_id_users')),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], name=op.f('fk_paiements_etablissement_id_etablissements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paiements')),
    sa.UniqueConstraint('reference_transaction', name=op.f('uq_paiements_reference_transaction'))
    )
    op.create_index(op.f('ix_paiements_apprenant_id'), 'paiements', ['apprenant_id'], unique=False)
    op.create_index(op.f('ix_paiements_etablissement_id'), 'paiements', ['etablissement_id'], unique=False)
    op.create_index(op.f('ix_paiements_reference_operateur'), 'paiements', ['reference_operateur'], unique=False)
    op.create_index(op.f('ix_paiements_statut'), 'paiements', ['statut'], unique=False)
    op.create_table('paiement_qrcodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paiement_id', sa.UUID(), nullable=False),
    sa.Column('type_code', sa.Enum('INFOS_APPRENANT', 'COMPTE_PAIEMENT', 'MONTANT', 'IDENTIFIANT_TRANSACTION', name='typeqrcode'), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('scanne', sa.String(length=1), nullable=True),
    sa.Column('scanne_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paiement_id'], ['paiements.id'], name=op.f('fk_paiement_qrcodes_paiement_id_paiements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paiement_qrcodes'))
    )
    op.create_index(op.f('ix_paiement_qrcodes_paiement_id'), 'paiement_qrcodes', ['paiement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paiement_qrcodes_paiement_id'), table_name='paiement_qrcodes')
    op.drop_table('paiement_qrcodes')
    op.drop_index(op.f('ix_paiements_statut'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_reference_operateur'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_etablissement_id'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_apprenant_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_matricule'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('etablissements')
    # ### end Alembic commands ###
