"""models update

Revision ID: ee4a6a96f3e2
Revises: da2cde4bfd36
Create Date: 2026-07-21 02:11:06.600871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4a6a96f3e2'
down_revision: Union[str, None] = 'da2cde4bfd36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objets_paiement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('etablissement_id', sa.UUID(), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('echeance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etablissement_id'], ['etablissements.id'], name=op.f('fk_objets_paiement_etablissement_id_etablissements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objets_paiement'))
    )
    op.create_index(op.f('ix_objets_paiement_etablissement_id'), 'objets_paiement', ['etablissement_id'], unique=False)
    op.create_table('quitus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('objet_paiement_id', sa.UUID(), nullable=False),
    sa.Column('apprenant_id', sa.UUID(), nullable=False),
    sa.Column('url_fichier', sa.String(length=255), nullable=False),
    sa.Column('taille_octets', sa.Integer(), nullable=True),
    sa.Column('deposee_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apprenant_id'], ['users.id'], name=op.f('fk_quitus_apprenant_id_users')),
    sa.ForeignKeyConstraint(['objet_paiement_id'], ['objets_paiement.id'], name=op.f('fk_quitus_objet_paiement_id_objets_paiement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quitus'))
    )
    op.create_index(op.f('ix_quitus_apprenant_id'), 'quitus', ['apprenant_id'], unique=False)
    op.create_index(op.f('ix_quitus_objet_paiement_id'), 'quitus', ['objet_paiement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quitus_objet_paiement_id'), table_name='quitus')
    op.drop_index(op.f('ix_quitus_apprenant_id'), table_name='quitus')
    op.drop_table('quitus')
    op.drop_index(op.f('ix_objets_paiement_etablissement_id'), table_name='objets_paiement')
    op.drop_table('objets_paiement')
    # ### end Alembic commands ###
